### ISSUE TITLE
[github-action] Do-not trigger unless if not commited in /data/ folder

### ISSUE THREAD

**Issue by akashp1712** [akashp1712/python-tricks#10]

**Comment by akashp1712** [comment]
Fixed the issue in commit: [Triggering the workflow only for `data` chnages ](https://github.com/akashp1712/python-tricks/commit/e7d85064bb224ead259b5a05cf1c6b05d743710e)

```
on:
  push:
    paths:
    - 'data/**.json'
    - '!data/0_metadata.json'
```
